### ISSUE TITLE
Month option

### ISSUE THREAD

**Issue by bonoirk** [Petro31/easy-time-jinja#32]
Is it possible to make the period to be displayed as follows (including division into months):
“1 year, 5 month, 2 weeks and 3 days ago”?

**Comment by Petro31** [comment]
No, month is not supported because it will slow the macro down considerably.  If every month had 30 days, it wouldn't be a problem.

**Comment by Mariusthvdb** [comment]
Understand.

tbh, I came here mostly because I noticed the difference in the frontend handling resulting in either 2 maanden or 3 months.....
the rounding seems huge, though technically correct.
We need a precision setting for the [frontend format options](https://www.home-assistant.io/dashboards/entities/#format) too ;-)
